FROM node:22-slim AS build

WORKDIR /build

COPY package.json ./

RUN node -v

RUN npm install

COPY . .

RUN env

RUN npm run generate

FROM busybox:1.35 AS run

RUN adduser -D static
USER static
WORKDIR /home/static

COPY --from=build /build/.output/public .

CMD ["busybox", "httpd", "-f", "-v", "-p", "3000"]