on:
  push:
    branches:
      - release

jobs:
  build:
    name: frontend-deployment
    runs-on: yetir_server
    steps:
      - uses: actions/checkout@v2
      - run: docker compose up -d --force-recreate
